language: node_js
node_js: "8"
branches:
  only:
  - master
cache:
  directories:
    - node_modules
services:
  - mongodb
before_install:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'